- src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestEhrEndpoint.java
- src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestEhrFieldsEndpointIT.java
Adds fixes for more strict EHRbase validation of openEHR RM objects. Also makes creation of EHR more leaner defaulting to server side created status instance (otherwise the client side one would need to comply to stricter validation, too).
> Fixes create EHR and linked test

- client/src/test/resources/simplelogger.properties
Sets client unit test logging to info level. This seems to fix VM crashes, due to a very high amount of logging.
> Fixes stability of unit tests

- .circleci/config.yml
- client/pom.xml
- generator/pom.xml
- opt-1.4/pom.xml
- pom.xml
- response-dto/pom.xml
- serialisation/pom.xml
- terminology/pom.xml
- test-data/pom.xml
- validation/pom.xml
this one is based on commit d97d209 which is used in EHRbase repo on development branch: `<ehrbase.sdk.version>d97d209</ehrbase.sdk.version>`
Using <ehrbase.sdk.version>v0.3.2-SNAPSHOT</ehrbase.sdk.version> in EHRbase's main pom works in both cases:
- locally (after `mvn install SDK) und and
- remotely (with clean ~/.m2 folder, then SDK dependencies are pulled from jitpack.io)
> Changes group ID to allow EHRbase build w/ locally installed SDK deps

- client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAqlEndpoint.java
- client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestClient.java
- client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestFolderDAO.java
- client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestTemplateEndpoint.java
The apache httpclient content type constants are designed to be used as
content-type header. They contain charset parameters, which are only
allowed as content-type header. For accept header scenarios there's a
specific accept-charset header.
This charset at the wrong place caused problems.
> Fixes usage of content type as accecpt header

- .circleci/config.yml
- client/pom.xml
- client/src/main/java/org/ehrbase/client/aql/containment/ContainmentPath.java
- client/src/test/java/org/ehrbase/client/aql/query/EntityQueryTest.java
- client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/CoronaTestIT.java
- client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAqlEndpointTestIT.java
- client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestTemplateEndpointIT.java
- generator/pom.xml
- opt-1.4/pom.xml
- pom.xml
- response-dto/pom.xml
- serialisation/pom.xml
- sonar-project.properties
- terminology/pom.xml
- test-coverage/pom.xml
- test-data/pom.xml
- validation/pom.xml
Implements jacoco code coverage measurement w/ proper support for default maven phases (test, verify, package, ...) and upload of code analysis from CI to sonarcloud.io
Now we can (locally and on CI):
`mvn clean test`
`mvn clean verify`       (integration tests are skipped by default)
`mvn clean package`      (integration tests are skipped by default)
`mvn clean install`      (integration tests are skipped by default)
...
`mvn clean verify -DskipIntegrationTests=false`
:warning: EHRbase server + DB must be running to execute integration tests successfully
`mvn clean -Pfast test` (will execute unit tests only)
`mvn clean -Pslow test` (will execute integration tests only)
`mvn clean -Pfull test` (will execute all test)
:warning: Final ~~configuration~~ activation of upload to sonarcloud.io …
> 304 add sonar analysis to ci pipeline

- .gitignore
- pom.xml
- Replaces junit(4) dependency w/ org.junit.vintage
- This allows to execute Junit4 tests w/ Junit5.
- Thus old tests can remain untouched while new tests can be written in Junit5 style (therefore also added org.junit.jupiter (Junit5) dependency)
> Upgrade to Junit5

- README.md
An existing 0.3.6-SNAPSHOT tag broke previous attempt
> Repeating auto version update

- .circleci/config.yml
The release branch is a short living one, it gets deleted automatically after merge thus sonar analysis triggered on release branch fails. Adding it to branches ignore filter in CI config should fix this.
> Skip sonar analysis on short living release branch

- .circleci/config.yml
Applied changes suggested by @StefanWinterfeldtVitasystems  as commended in https://github.com/ehrbase/openEHR_SDK/pull/49#pullrequestreview-479670353
- (short living) release branch is merged into master
- release branch is when deleted from remote
- master is merged back into develop
- result: master and develop are in sync
- git history states clearly: NEW RELEASE VERSION ...
@StefanWinterfeldtVitasystems I've thoroughly tested this change in a playground repo, feel free to check it's [commit history](https://github.com/testautomation/ci-playground-openehr-sdk/commits/develop).
closes https://github.com/ehrbase/project_management/issues/292
> Update openEHR_SDK CI pipeline - removes `git --hard reset`

- CHANGELOG.md
- client/src/main/java/org/ehrbase/client/aql/containment/Containment.java
- client/src/main/java/org/ehrbase/client/aql/field/NativeSelectAqlField.java
- client/src/test/java/org/ehrbase/client/aql/query/EntityQueryTest.java
- client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/AqlTestIT.java
closes https://github.com/ehrbase/openEHR_SDK/issues/91
> allow native parts in EntityQuery

- .circleci/config.yml
- Renamed main CI workflows into QUALITY GATE I and II
- fixed issue where CI cache prevented EHRbase build to fail when it actually should fail due to changes in the SDK
- builds and tests SDK as fast as possible for fast feedback
- ehrbase build w/o any tests (mvn even doesn't compile any test code)
- no Jacoco code instrumentation
- no code coverage metrics and related storage/upload of artifacts
- no Java Doc generation
- needs less than 50% of time before Robot integration test can start than would be the case in Quality Gate 2
- Jacoco code instrumentation enabled to get coverage metrics
- ehrbase build with tests enabled
- Java docs generation enabled
- Sonar code analysis enabled and results uploaded to sonarcloud.io
- TODO: enable scheduled execution(?)
- TODO: add security test …
> Feature/enhance CI config

- validation/src/main/java/org/ehrbase/validation/constraints/wrappers/IntervalComparator.java
This fix check that DvDuration interval set as boundaries in a template is using DURATION (and not PERIOD). The reason is that a PERIOD cannot be normalized for comparison: 1M could hold value of 28D, 29D, 30D, 31D. The same for year vs days.
Hence, whenever boundaries are defined there should be DURATION only, that is "PT...".
Fixes: https://github.com/ehrbase/ehrbase/issues/427
> force duration for DvDuration boundaries

- validation/src/main/java/org/ehrbase/validation/constraints/wrappers/IntervalComparator.java
DvDuration is not comparable due to the period part (year, month, week). Hence a validation if a value is within an interval cannot be performed. This particular test is now disable until DvDuration as a type is fixed.
> Disable validation of openEHR "Duration" instances.

- serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/CompositionSerializer.java
- serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/translator_db2raw/LinkedTreeMapAdapter.java
- serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/translator_db2raw/OptOut.java
removed epoch_offset from canonical DvDateTime rendering.
Fixes: https://github.com/ehrbase/project_management/issues/408
NB. The test fails due to unresolved https://github.com/ehrbase/project_management/issues/361. This means that until the recommended step is not done, this change cannot be merged.
> allow opt-out on specific attributes in canonical json

- serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/CodePhraseAdapter.java
- serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/DvCodedTextAdapter.java
This fix remove the name (operation, not an attribute) in canonical TERMINOLOGY_ID rendering.
Fixes: https://github.com/ehrbase/project_management/issues/465
> removed name json encoding

- serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/translator_db2raw/GenericRmType.java
removed the specialization for DV_INTERVAL:
- before a type could come out as: `DV_INTERVAL<DV_COUNT>`
- now: `DV_INTERVAL` as expected
Fixes: https://github.com/ehrbase/project_management/issues/466
> removed specialization in DV_INTERVAL type expression

- client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/systematic/SpecialCase.java
- client/src/test/resources/testsets/arbitrary/date_time_where_tests.csv
- serialisation/src/main/java/org/ehrbase/serialisation/jsonencoding/CanonicalJson.java
- serialisation/src/main/java/org/ehrbase/serialisation/jsonencoding/DateTimeSerializer.java
- serialisation/src/test/java/org/ehrbase/serialisation/jsonencoding/CanonicalJsonMarshallingTest.java
This change normalize DOT as decimal separator in ISO8601 datetime representation whenever milliseconds are present. That is:
```
2021-10-01T10:32:51.543+07:00
```
Canonical json is now properly encoded (previously due to Archie serialization, the delimiter was a COMMA).
This fixes: https://github.com/ehrbase/project_management/issues/453
> use custom serializer for DvDateTime

- validation/src/main/java/org/ehrbase/validation/constraints/OptConstraintMapper.java
Fixes null `ccomplexobject` when Validator instance is deserialized from cache (Redis or EhCache + persitence)
> Fixes null ccomplexobject when Validator instance is deserialized

- serialisation/src/main/java/org/ehrbase/serialisation/attributes/LocatableAttributes.java
- serialisation/src/main/java/org/ehrbase/serialisation/jsonencoding/JacksonUtil.java
Constrained json encoding to remove the operations (aka. attributes) unexpected in archetype_id (see https://specifications.openehr.org/releases/UML/latest/#Architecture___18_5_1_83e026d_1503073094506_395796_7676) 
fixes: https://github.com/ehrbase/ehrbase/issues/446
fixes: https://github.com/ehrbase/project_management/issues/586
> constrain encoding

- CHANGELOG.md
- building/pom.xml
- pom.xml
- response-dto/pom.xml
- serialisation/pom.xml
- terminology/pom.xml
- validation/pom.xml
- web-template/pom.xml
Upgrade to archie 1.0.4 (CDR-156)
> Upgrade to archie 1.0.4

- CHANGELOG.md
- serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/SerialTree.java
- serialisation/src/test/java/org/ehrbase/serialisation/dbencoding/RawJsonTest.java
- test-data/src/main/java/org/ehrbase/test_data/composition/CompositionTestDataCanonicalJson.java
- test-data/src/main/resources/composition/canonical_json/gecco_laborbefund.json
Fixes NullPointerException when event has an empty state (ehrbase/ehrbase#543)
> Fixes NullPointerException when event has an empty state

- CHANGELOG.md
- client/src/main/java/org/ehrbase/client/openehrclient/AdminTemplateEndpoint.java
- client/src/main/java/org/ehrbase/client/openehrclient/OpenEhrClient.java
- client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAdminTemplateEndpoint.java
- client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestClient.java
- client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestTemplateEndpointIT.java
fixes: https://github.com/ehrbase/openEHR_SDK/issues/298
> added admin point to delete templates

- CHANGELOG.md
- serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/PartyRefAdapter.java
- serialisation/src/test/java/org/ehrbase/serialisation/dbencoding/DBEncodeTest.java
This is simply adding the attribute `type` to json ExternalRef serialization.
fixes: https://github.com/ehrbase/ehrbase/issues/729
> added missing type attribute in jsonb encoding

- client/src/main/java/org/ehrbase/client/flattener/DtoFromCompositionWalker.java
Use Introspector::getBeanInfo instead of manually creating PropertyDescriptors
> Describe your changes in a short and concise list.
> CDR-912 fix DtoFromCompositionWalker::extractAttribute

- README.md
- serialisation/src/main/java/org/ehrbase/openehr/sdk/serialisation/flatencoding/std/marshal/config/DvOrdinalConfig.java
- serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/flatencoding/std/marshal/config/DvOrdinalConfigTest.java
Update flat marshalling of DvOrdered to be more resilient by not looking into the context.
also: corrected formatter usage in Readme so it now matches the values defined in the pom spotless config.
> CDR-1388 Update flat marshalling of DvOrdered to be more resilient

- CHANGELOG.md
- response-dto/src/main/java/org/ehrbase/openehr/sdk/response/dto/MetaData.java
- response-dto/src/test/java/org/ehrbase/openehr/sdk/response/dto/MetaDataTest.java
Add EHRbase debug execution data to `MetaData` repsonse.
> [CDR-1397] Add Execution info to MetaData

- CHANGELOG.md
- response-dto/src/main/java/org/ehrbase/openehr/sdk/response/dto/ContributionCreateDto.java
- response-dto/src/main/java/org/ehrbase/openehr/sdk/response/dto/EhrResponseData.java
- response-dto/src/main/java/org/ehrbase/openehr/sdk/response/dto/EhrStatusResponseData.java
- response-dto/src/main/java/org/ehrbase/openehr/sdk/response/dto/VersionedCompositionResponseData.java
- response-dto/src/main/java/org/ehrbase/openehr/sdk/response/dto/VersionedObjectResponseData.java
- response-dto/src/main/java/org/ehrbase/openehr/sdk/response/dto/ehrscape/EhrStatusDto.java
Some of the response DTOs/Data classes are only used by EHRbase. This PR deprecates them because they are now moved over to EHtbase itself https://github.com/ehrbase/ehrbase/pull/1377.
> [CDR-1506] Deprecate DTOs/Data classes for EHR(_STATUS) used by EHRbase

- aql/src/main/java/org/ehrbase/openehr/sdk/aql/util/AqlUtil.java
- aql/src/test/java/org/ehrbase/openehr/sdk/aql/util/AqlUtilTest.java
The method  `AqlUtil.removeParameter()` currently does only support WhereConditions that are an instance of ComparisonOperatorCondition or LogicalOperatorCondition, i.e. parameters contained in other conditions are not removed.
This PR changes the method so that is also works with NotConditions, MatchesConditions and LikeConditions.
-
> Add support for NOT, MATCHES and LIKE conditions to AqlUtil.removeParameter
