ehrbase/openEHR_SDK

serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/CompositionSerializer.java

See https://github.com/ehrbase/ehrbase/pull/257 for details.

migration of PR https://github.com/ehrbase/ehrbase/pull/257

---

.circleci/config.yml

Initial CI worklow
- build and unit test SDK
- build and unit test EHRbase (w/ SDK as dependency)
- optionally automatically creates [major minor patch] SNAPSHOT release from develop branch
- integration tests are there but mocked out to speed up further iterations during final implementation
- not yet implemented: optionally creates [major minor patch] STABLE release from master

ci activation

---

client/src/main/java/org/ehrbase/client/openehrclient/EhrEndpoint.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestEhrEndpoint.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestEhrFieldsEndpointIT.java

Closes https://github.com/ehrbase/project_management/issues/307

Adds create EHR with EHR_STATUS client method

---

response-dto/src/main/java/org/ehrbase/response/openehr/admin/AdminDeleteResponseData.java
response-dto/src/main/java/org/ehrbase/response/openehr/admin/AdminStatusResponseData.java
response-dto/src/main/java/org/ehrbase/response/openehr/admin/AdminUpdateResponseData.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/CompositionSerializer.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/rawjson/LightRawJsonEncoder.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/translator_db2raw/ArchieCompositionProlog.java
test-data/src/main/java/org/ehrbase/test_data/composition/CompositionTestDataCanonicalJson.java

See http://docs.ehrbase.org/en/latest/03_development/02_technical_docs/index.html#new-contain-clause-resolution-strategy for details.

281_serialization_for_new_containment_ns

---

response-dto/pom.xml
response-dto/src/main/java/org/ehrbase/response/ehrscape/QueryResultDto.java
response-dto/src/main/java/org/ehrbase/response/ehrscape/query/ResultHolder.java
response-dto/src/main/java/org/ehrbase/response/openehr/QueryResponseData.java

see https://github.com/ehrbase/ehrbase/pull/290 for details

allow duplicate column id in AQL result set

---

serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/translator_db2raw/LinkedTreeMapAdapter.java

This fixes issue: https://github.com/ehrbase/project_management/issues/331 (item # 1)

remove archetype_node_id handling for composition

---

.circleci/config.yml

see comment --> https://github.com/ehrbase/project_management/issues/304#issuecomment-674758262

Activate sonar analysis

---

generator/src/test/java/org/ehrbase/client/classgenerator/ClassGeneratorTest.java
pom.xml
sonar-project.properties
test-coverage/pom.xml

- excludes test code from sonar analysis
- and some other litte test fixes

Updates version of surefire, failsafe and jacoco

---

serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/translator_db2raw/ArrayChildren.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/translator_db2raw/LinkedTreeMapAdapter.java

See https://github.com/ehrbase/ehrbase/pull/326

Mostly cosmetic changes to deal with empty struct

---

serialisation/src/test/java/org/ehrbase/serialisation/dbencoding/DBEncodeTest.java
test-data/src/main/java/org/ehrbase/test_data/composition/CompositionTestDataCanonicalJson.java
test-data/src/main/resources/composition/canonical_json/duration_tests.json

A couple of simple tests to check DvDuration support in Archie.
NB. negative duration is not supported well: https://github.com/openEHR/archie/issues/209

added jUnit to check support of DvDuration

---

serialisation/src/main/java/org/ehrbase/serialisation/attributes/ElementAttributes.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/NameAsDvText.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/DvCodedTextAdapter.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/DvTextAdapter.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/translator_db2raw/DvCodedTextNameValue.java
serialisation/src/test/java/org/ehrbase/serialisation/dbencoding/DBEncodeTest.java

Fixed multiple formatting issues. The type is now explicitly added to the data value json expression.
See https://github.com/ehrbase/ehrbase/pull/338
Fixes: https://github.com/ehrbase/project_management/issues/236

Added explicit type in db serialization

---

client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAqlEndpoint.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestClient.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestFolderDAO.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestTemplateEndpoint.java

DefaultRestAqlEndpoint uses config correctly

---

.circleci/config.yml

- Adopts QUERYSERVICE-test-2 CI job from EHRbase's CI pipeline
- Speeds up QUERYSERVICE test suite by utilizing dump/restore DB
- Overall build time reduction of almost 50%

Fix QUERYSERVICE-test-2 CI Job

---

response-dto/src/main/java/org/ehrbase/response/openehr/EhrResponseData.java

see see https://github.com/ehrbase/project_management/issues/410

fixed EhrResponseData

---

serialisation/src/main/java/org/ehrbase/serialisation/attributes/LocatableAttributes.java
serialisation/src/test/java/org/ehrbase/serialisation/dbencoding/DBEncodeTest.java
test-data/src/main/java/org/ehrbase/test_data/composition/CompositionTestDataCanonicalJson.java
test-data/src/main/resources/composition/canonical_json/demo_vitals_352.json

Fix wrong db encoding for archetype_details attribute in content.
Fixes issue: https://github.com/ehrbase/ehrbase/issues/352

fix bad encoding

---

CHANGELOG.md
client/src/main/java/org/ehrbase/client/openehrclient/TemplateEndpoint.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAqlEndpoint.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestClient.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestTemplateEndpoint.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestTemplateEndpointIT.java
response-dto/src/main/java/org/ehrbase/response/openehr/TemplatesResponseData.java

Added getAllTemplates endpoint to TemplateEndpoint
Relates to: https://jira.vitagroup.ag/browse/NUM-435

Added getAllTemplates endpoint to TemplateEndpoint

---

CHANGELOG.md
client/src/main/java/org/ehrbase/client/openehrclient/TemplateEndpoint.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAqlEndpoint.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestClient.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestTemplateEndpoint.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestTemplateEndpointIT.java
response-dto/src/main/java/org/ehrbase/response/openehr/TemplatesResponseData.java

Added getAllTemplates endpoint to TemplateEndpoint
Relates to: https://jira.vitagroup.ag/browse/NUM-435

Feature danielatomoiaga/get all templates endpoint

---

.github/ISSUE_TEMPLATE/defect(robot).md
.github/ISSUE_TEMPLATE/defect.md
.github/ISSUE_TEMPLATE/feature-story.md
.github/ISSUE_TEMPLATE/task.md

- Add version information for bug issue template
- Change advices in all templates to be comments

[skip ci] Add versions to bug issue template

---

.circleci/config.yml

Test tags in EHRbase's Robot test suites and test cases were changed. This PR adjusts SDK's CI pipeline to this changes.

Feature/adapt ehrbases test tag changes in SDK's CI pipeline

---

serialisation/src/main/java/org/ehrbase/serialisation/attributes/EntryAttributes.java

this is the PR in sync with https://github.com/ehrbase/ehrbase/pull/425

added test method for entry attributes

---

aql/src/main/java/org/ehrbase/aql/binder/WhereBinder.java
aql/src/main/java/org/ehrbase/aql/dto/condition/MatchesOperatorDto.java
aql/src/main/java/org/ehrbase/aql/parser/AqlToDtoVisitor.java
aql/src/test/java/org/ehrbase/aql/parser/AqlToDtoParserTest.java
client/src/main/java/org/ehrbase/client/aql/condition/BinaryLogicalOperator.java
client/src/main/java/org/ehrbase/client/aql/condition/ComparisonOperator.java
client/src/main/java/org/ehrbase/client/aql/condition/Condition.java
client/src/main/java/org/ehrbase/client/aql/condition/Exists.java
client/src/main/java/org/ehrbase/client/aql/condition/Matches.java
client/src/main/java/org/ehrbase/client/aql/condition/Not.java
client/src/main/java/org/ehrbase/client/aql/field/AqlFieldImp.java
client/src/main/java/org/ehrbase/client/aql/field/SelectAqlField.java
client/src/main/java/org/ehrbase/client/aql/orderby/AbstractOrderBy.java
client/src/main/java/org/ehrbase/client/aql/orderby/AndThen.java
client/src/main/java/org/ehrbase/client/aql/orderby/OrderByExpression.java
client/src/main/java/org/ehrbase/client/aql/query/EntityQuery.java
client/src/test/java/org/ehrbase/client/aql/condition/ConditionTest.java

closes https://github.com/ehrbase/openEHR_SDK/issues/187

add support for matches in Aql binding and parsing.

---

.circleci/config.yml
README.md

- to make step which changes version in EHRbase's pom more verbose
- cat pom.xml to check version was updated correctly

[UPDATE] CI config

---

building/pom.xml
pom.xml
serialisation/pom.xml
serialisation/src/main/java/org/ehrbase/serialisation/attributes/FeederAuditDetailsAttributes.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/rawjson/LightRawJsonEncoder.java
serialisation/src/test/java/org/ehrbase/serialisation/dbencoding/DBEncodeTest.java
test-data/src/main/java/org/ehrbase/test_data/composition/CompositionTestDataCanonicalJson.java
test-data/src/main/resources/composition/canonical_json/compo_feeder_audit_details.json

feeder audit's other details and version id are now supported
fixes https://github.com/ehrbase/project_management/issues/514

Adds more feeder audit handling in serialization

---

serialisation/src/main/java/org/ehrbase/serialisation/attributes/FeederAuditDetailsAttributes.java
serialisation/src/test/java/org/ehrbase/serialisation/attributes/FeederAuditDetailsAttributesTest.java
serialisation/src/test/java/org/ehrbase/serialisation/dbencoding/DBEncodeTest.java

fixes https://github.com/ehrbase/project_management/issues/514

Fixes feeder audit other details node path naming

---

client/src/test/resources/testsets/arbitrary/arbitrary_boolean_where_tests.csv

related to and have to be merged together (at the same time) with https://github.com/ehrbase/ehrbase/pull/488

adapted query test

---

aql/src/test/java/org/ehrbase/aql/parser/AqlToDtoParserTest.java
client/src/main/java/org/ehrbase/client/aql/query/EntityQuery.java

closes https://github.com/ehrbase/openEHR_SDK/issues/216

aql generation make names unique

---

CHANGELOG.md
aql/src/main/java/org/ehrbase/aql/parser/AqlToDtoVisitor.java
aql/src/main/java/org/ehrbase/aql/util/AqlUtil.java
aql/src/test/java/org/ehrbase/aql/parser/AqlToDtoParserTest.java
aql/src/test/java/org/ehrbase/aql/util/AqlUtilTest.java

closes https://github.com/ehrbase/project_management/issues/547
closes #224

Provide utility to remove parameters within AQL WHERE clauses

---

client/src/main/java/org/ehrbase/client/openehrclient/CompositionEndpoint.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestClient.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestCompositionEndpoint.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestCompositionEndpointIT.java

Resolves ehrbase/project_management#543

Implements 'Delete composition' operation

---

validation/src/main/java/org/ehrbase/validation/constraints/terminology/FhirTerminologyValidationSupport.java
validation/src/test/java/org/ehrbase/validation/constraints/DvCodedTextExternalTerminologyIT.java
validation/src/test/resources/constraints/terminology/fhir_codesystem.xml
validation/src/test/resources/constraints/terminology/fhir_valueset.xml

Updates CodeSystem and ValueSet used in the integration tests.

Updates CodeSystem and ValueSet used in integration tests.

---

validation/pom.xml
validation/src/test/java/org/ehrbase/validation/constraints/DvCodedTextExternalTerminologyIT.java
validation/src/test/java/org/ehrbase/validation/constraints/DvCodedTextExternalTerminologyTest.java

- Implements unit tests using Mockito.
- Disables integration tests by default.

Fix integration tests regarding external terminology validation

---

CHANGELOG.md
client/pom.xml
client/src/main/java/org/ehrbase/client/annotations/Archetype.java
client/src/main/java/org/ehrbase/client/annotations/Choice.java
client/src/main/java/org/ehrbase/client/annotations/Entity.java
client/src/main/java/org/ehrbase/client/annotations/Id.java
client/src/main/java/org/ehrbase/client/annotations/OptionFor.java
client/src/main/java/org/ehrbase/client/annotations/Path.java
client/src/main/java/org/ehrbase/client/annotations/Template.java
client/src/main/java/org/ehrbase/client/flattener/DtoFromCompositionWalker.java
client/src/main/java/org/ehrbase/client/flattener/DtoToCompositionWalker.java
client/src/main/java/org/ehrbase/client/flattener/Flattener.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestCompositionEndpoint.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/BloodPressureTrainingSampleObservationProxy.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAqlEndpointTestIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestCompositionEndpointIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/ProxyEhrbaseBloodPressureSimpleDeV0Composition.java
pom.xml
util/src/main/java/org/ehrbase/util/reflection/ReflectionHelper.java

closes https://github.com/ehrbase/openEHR_SDK/issues/243

added  @Inherited annotation to dtos annotations

---

CHANGELOG.md
terminology/src/main/java/org/ehrbase/terminology/openehr/implementation/AttributeCodesetMapping.java
terminology/src/main/resources/attribute_to_openehr_codesets.xml
validation/src/main/java/org/ehrbase/validation/terminology/validator/TerminologyCheck.java
validation/src/test/java/org/ehrbase/validation/ItemStructureVisitorTest.java
validation/src/test/resources/composition/IDCR-LabReportRAW1.xml
validation/src/test/resources/composition/IDCR-LabReportRAW1_with_normal_status.xml

closes https://github.com/ehrbase/openEHR_SDK/issues/248

 fix validate normal statuses

---

client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/CoronaTestIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAdminEhrEndpointIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestCompositionEndpointIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestDirectoryEndpointIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestEhrFieldsEndpointIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestVersionedCompositionEndpointIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/systematic/compositionquery/ArbitraryQueryOtherContextIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/systematic/compositionquery/AutoWhereIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/systematic/ehrquery/CanonicalEhrQuery1IT.java

See https://github.com/ehrbase/ehrbase/pull/571 for details

added tearDown() with EHR deletion in tests

---

.circleci/config.yml
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/systematic/compositionquery/AutoWhereIT.java
client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/systematic/compositionquery/SelectRMIT.java

see https://jira.vitagroup.ag/browse/PEA-163

reenable  test

---

CHANGELOG.md
opt-1.4/src/main/xsd/Template.xsd
web-template/src/main/java/org/ehrbase/webtemplate/parser/OPTParser.java

enhance opt parsing performance

---

.github/workflows/build.yml
aql/pom.xml
building/pom.xml
building/src/main/java/org/ehrbase/building/OptSkeletonBuilder.java
client/pom.xml
generator/pom.xml
opt-1.4/pom.xml
pom.xml
response-dto/pom.xml
serialisation/pom.xml
serialisation_conformance_test/pom.xml
terminology/pom.xml
terminology/src/main/java/org/ehrbase/terminology/openehr/TerminologyService.java
terminology/src/main/java/org/ehrbase/terminology/openehr/implementation/SimpleTerminologyAccess.java
test-coverage/pom.xml
test-data/pom.xml
util/pom.xml
validation/pom.xml
validation/src/main/java/org/ehrbase/validation/constraints/hardwired/StructureConstraint.java
validation/src/main/java/org/ehrbase/validation/constraints/wrappers/CAttribute.java
validation/src/main/java/org/ehrbase/validation/constraints/wrappers/CBoolean.java
validation/src/main/java/org/ehrbase/validation/constraints/wrappers/CComplexObject.java
validation/src/main/java/org/ehrbase/validation/constraints/wrappers/CDate.java
validation/src/main/java/org/ehrbase/validation/constraints/wrappers/CDateTime.java
validation/src/main/java/org/ehrbase/validation/constraints/wrappers/CDefinedObject.java
validation/src/main/java/org/ehrbase/validation/constraints/wrappers/CDomainType.java
validation/src/main/java/org/ehrbase/validation/constraints/wrappers/CDuration.java
validation/src/main/java/org/ehrbase/validation/constraints/wrappers/CPrimitive.java
validation/src/main/java/org/ehrbase/validation/terminology/ItemStructureVisitor.java
web-template/pom.xml

Publish artifacts (snapshots and releases) on Maven Central

Cdr 15 maven central

---

serialisation/src/main/java/org/ehrbase/serialisation/walker/Walker.java
serialisation/src/test/java/org/ehrbase/serialisation/walker/WalkerTest.java

closes https://github.com/ehrbase/ehrbase/issues/696

walker needs to work on a clone

---

.github/workflows/build.yml
pom.xml

- Replace `maven-deploy-plugin` by `nexus-staging-maven-plugin`
- Fixes coverage issue

Fixes coverage issue and auto-close staging repository

---

test-data/src/main/java/org/ehrbase/test_data/operationaltemplate/OperationalTemplateTestData.java
test-data/src/main/resources/operationaltemplate/multimedia_test.en.v1.opt
web-template/src/test/java/org/ehrbase/webtemplate/parser/OPTParserTest.java

Add unit test to check that provided template is not failing after the refactoring done by @stefanspiska   (ehrbase/project_management#297 / CDR-24)

PARTICIPATION not handled by OptVisitor (WebTemplate)

---

client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/ParticipationTestIT.java
test-data/src/main/java/org/ehrbase/test_data/composition/CompositionTestDataCanonicalJson.java
test-data/src/main/resources/composition/canonical_json/participation_no_content.json

Forgot to add this as a PR :-(

added tests for context/participation

---

CHANGELOG.md
aql/pom.xml
aql/src/main/antlr4/org/ehrbase/aql/parser/Aql.g4
aql/src/main/java/org/ehrbase/aql/parser/AqlToDtoVisitor.java
aql/src/test/java/org/ehrbase/aql/parser/AqlToDtoParserTest.java

Fixes issue in AQL regarding LIMIT and OFFSET

Fixes issue in AQL regarding LIMIT and OFFSET

---

client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/OtherParticipationsQueryTestIT.java
test-data/src/main/java/org/ehrbase/test_data/composition/CompositionTestDataCanonicalJson.java
test-data/src/main/resources/composition/canonical_json/other_participations.json

See https://github.com/ehrbase/ehrbase/pull/730

added tests for other_participations querying

---

serialisation/src/main/java/org/ehrbase/serialisation/jsonencoding/DateTimeSerializer.java
serialisation/src/test/java/org/ehrbase/serialisation/jsonencoding/CanonicalJsonMarshallingTest.java
serialisation_conformance_test/pom.xml
serialisation_conformance_test/src/test/java/org/ehrbase/conformance_test/extern/tests/EndTimeTestOverwrite.java
serialisation_conformance_test/src/test/java/org/ehrbase/conformance_test/extern/tests/FeederAuditTestOverwritten.java
serialisation_conformance_test/src/test/java/org/ehrbase/conformance_test/extern/tests/HistoryOriginTestOverwrite.java
serialisation_conformance_test/src/test/java/org/ehrbase/conformance_test/extern/tests/LocationTestOverwrite.java
serialisation_conformance_test/src/test/java/org/ehrbase/conformance_test/extern/tests/TimeZoneTestOverwrite.java

see https://jira.vitagroup.ag/browse/CDR-232

fix dv_date_time format

---

pom.xml
web-template/src/main/java/org/ehrbase/webtemplate/model/WebTemplateNode.java
web-template/src/test/java/org/ehrbase/webtemplate/parser/OPTParserTest.java

This PR fixes the ClassCastException that currently occurs while serializing the Web Template in JSON

Fixes ClassCastException while serializing WebTemplate

---

CHANGELOG.md
aql/src/main/java/org/ehrbase/aql/dto/condition/SimpleValue.java
aql/src/main/java/org/ehrbase/aql/parser/AqlToDtoParser.java
aql/src/main/java/org/ehrbase/aql/parser/AqlToDtoVisitor.java
aql/src/test/java/org/ehrbase/aql/parser/AqlToDtoParserTest.java

Fixes #336 - AqlParseException while using boolean value in where clause.

Fixes AqlParseException while using boolean in where clause

---

serialisation/src/main/java/org/ehrbase/serialisation/jsonencoding/CanonicalJson.java

The resetup of the ObjectMapper module in CanonicalJson::marshal is unnecessary and since the same module is added over and over again degrades performance over time

Use a static ObjectMapper for marshaling in CanonicalJson

---

client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/systematic/compositionquery/CartesianProductQueryIT.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/wrappers/json/writer/translator_db2raw/LinkedTreeMapAdapter.java

trivial fix for https://github.com/ehrbase/ehrbase/issues/808

fixed NPE and test

---

.github/workflows/release.yml
.github/workflows/status.yml
CHANGELOG.md

add release action
see CDR-323

created release action

---

client/src/main/java/org/ehrbase/client/aql/parameter/AqlValue.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAqlEndpoint.java
client/src/test/java/org/ehrbase/client/classgenerator/OldDtoModelTest.java
client/src/test/java/org/ehrbase/client/flattener/RoundTripTest.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/RawJson.java
serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/rmobject/LinksEncoding.java
serialisation/src/main/java/org/ehrbase/serialisation/flatencoding/std/marshal/FlatJsonMarshaller.java
serialisation/src/main/java/org/ehrbase/serialisation/flatencoding/std/umarshal/FlatJsonUnmarshaller.java
serialisation/src/main/java/org/ehrbase/serialisation/flatencoding/std/umarshal/StdToCompositionWalker.java
serialisation/src/main/java/org/ehrbase/serialisation/flatencoding/std/umarshal/postprocessor/AbstractUnmarshalPostprocessor.java
serialisation/src/main/java/org/ehrbase/serialisation/flatencoding/std/umarshal/rmunmarshaller/AbstractRMUnmarshaller.java
serialisation/src/main/java/org/ehrbase/serialisation/flatencoding/structured/StructuredHelper.java
serialisation/src/main/java/org/ehrbase/serialisation/jsonencoding/ArchieObjectMapperProvider.java
serialisation/src/main/java/org/ehrbase/serialisation/jsonencoding/CanonicalJson.java
serialisation/src/main/java/org/ehrbase/serialisation/walker/defaultvalues/DefaultValues.java
serialisation/src/test/java/org/ehrbase/serialisation/flatencoding/std/marshal/FlatJsonMarshallerTest.java
serialisation/src/test/java/org/ehrbase/serialisation/flatencoding/std/umarshal/FlatJsonUnmarshallerTest.java
serialisation/src/test/java/org/ehrbase/serialisation/walker/defaultvalues/DefaultValuesTest.java
serialisation_conformance_test/src/test/java/org/ehrbase/conformance_test/db/DbConformanceTest.java
serialisation_conformance_test/src/test/java/org/ehrbase/conformance_test/extern/CompositionConverterImp.java
serialisation_conformance_test/src/test/java/org/ehrbase/conformance_test/flat/FlatConformanceTest.java
validation/src/test/java/org/ehrbase/validation/ItemStructureVisitorTest.java

dont modify shared objectmappers

---

client/src/main/java/org/ehrbase/client/flattener/Flattener.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAqlEndpoint.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestCompositionEndpoint.java
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestVersionedCompositionEndpoint.java

Allow to use custom class loaders in composition endpoint

---

serialisation/src/main/java/org/ehrbase/serialisation/matrixencoding/MatrixFormat.java

only encode json

---

aql/src/main/java/org/ehrbase/aql/dto/condition/ConditionComparisonOperatorSymbol.java
aql/src/main/java/org/ehrbase/aql/dto/condition/ConditionLogicalOperatorDto.java
aql/src/main/java/org/ehrbase/aql/dto/condition/LogicalOperatorDto.java
aql/src/main/java/org/ehrbase/aql/dto/condition/ParameterValue.java
aql/src/main/java/org/ehrbase/aql/dto/condition/SimpleValue.java
aql/src/main/java/org/ehrbase/aql/dto/containment/Containment.java
aql/src/main/java/org/ehrbase/aql/dto/containment/ContainmentLogicalOperator.java
aql/src/main/java/org/ehrbase/aql/dto/path/AqlPath.java
aql/src/main/java/org/ehrbase/aql/dto/path/predicate/PredicateComparisonOperatorDto.java
aql/src/main/java/org/ehrbase/aql/dto/path/predicate/PredicateHelper.java
aql/src/main/java/org/ehrbase/aql/dto/path/predicate/PredicateLogicalAndOperation.java
aql/src/main/java/org/ehrbase/aql/dto/path/predicate/PredicateLogicalOrOperation.java
aql/src/main/java/org/ehrbase/aql/parser/AqlToDtoVisitor.java
aql/src/main/java/org/ehrbase/aql/util/AqlUtil.java
aql/src/main/java/org/ehrbase/aql/util/CharSequenceHelper.java
aql/src/test/java/org/ehrbase/aql/dto/path/predicate/PredicateHelperTest.java
aql/src/test/java/org/ehrbase/aql/parser/AqlToDtoParserTest.java
aql/src/test/java/org/ehrbase/aql/util/CharSequenceHelperTest.java
web-template/src/main/java/org/ehrbase/webtemplate/interpreter/Interpreter.java

- PredicateLogicalAndOperation immutable
- introduced CharSequenceHelper::trim

CDR-587 Make AqlPath immutable

---

CHANGELOG.md
client/src/main/java/org/ehrbase/client/openehrclient/defaultrestclient/DefaultRestAqlEndpoint.java

add null verification and change gson to jackson

---

.github/workflows/codeql.yml

Added CodeQL GitHub action to scan for security issues.

Add CodeQL GitHub action

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/codeql.yml

Update github actions versions to latest and added dependabot support for them

Update github actions versions and add dependabot support for actions

---

bom/pom.xml

Add missing test scope to assertj dependency

Adjust assertj scope to test and sort test dependency in bom to the end

---

aql/src/main/java/org/ehrbase/openehr/sdk/aql/util/AqlUtil.java
bom/pom.xml

> Describe your changes in a short and concise list.

added AqlUtil::stream*  + cleanup pom

---

.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/report-sonar-results.yml

Update the access token used by the GitHub actions

Update secret used in GitHub actions

---

CHANGELOG.md
serialisation/src/main/java/org/ehrbase/openehr/sdk/serialisation/flatencoding/std/umarshal/postprocessor/LocatableUnmarshalPostprocessor.java
serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/FolderSerializerTest.java
serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/flatencoding/FlatJsonTest.java
serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/flatencoding/FlatTestHelper.java
serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/flatencoding/std/marshal/FlatJsonMarshallerTest.java
serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/flatencoding/std/umarshal/FlatJsonUnmarshallerTest.java
serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/flatencoding/structured/StructuredHelperTest.java
serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/jsonencoding/CanonicalJsonMarshallingTest.java
serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/walker/WalkerTest.java
serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/walker/defaultvalues/DefaultValuesTest.java
serialisation/src/test/java/org/ehrbase/openehr/sdk/serialisation/xmlencoding/CanonicalXMLTest.java

Fix for: https://github.com/ehrbase/ehrbase/issues/1368
- Fix flat format parsing of `ObjectVersionId`
- Add tests to ensure `ObjectVersionId` are parsed correctly
- Tweaked setup of Flat de-/-Serialization

[CDR-1512] Fix flat parsing of ObjectVersionId

---

util/src/main/java/org/ehrbase/openehr/sdk/util/rmconstants/RmConstants.java

CDR-1551 Add FOLDER to RMConstants

---

bom/pom.xml
web-template/pom.xml

> Describe your changes in a short and concise list.

remove commons-csv dependency

---

.github/workflows/report-sonar-results.yml

Use workflow_run head repo for checkout action of sonar report

Fix sonar report for external PRs

---

aql/src/main/java/org/ehrbase/openehr/sdk/aql/dto/operand/DoublePrimitive.java
aql/src/main/java/org/ehrbase/openehr/sdk/aql/dto/operand/PathPredicateOperand.java
aql/src/main/java/org/ehrbase/openehr/sdk/aql/dto/operand/Primitive.java
aql/src/main/java/org/ehrbase/openehr/sdk/aql/dto/operand/QueryParameter.java
aql/src/main/java/org/ehrbase/openehr/sdk/aql/dto/operand/StringPrimitive.java
aql/src/main/java/org/ehrbase/openehr/sdk/aql/dto/path/AqlObjectPath.java
aql/src/main/java/org/ehrbase/openehr/sdk/aql/render/AqlRenderer.java

> Describe your changes in a short and concise list.

CDR-2014 Refactoring: Introduce PathPredicateOperand::render
